import { useState } from 'react';
import { Sparkles, Save, PlusCircle, Eraser } from 'lucide-react';
import { useData } from '../context/DataContext';
import { aiTaskTypes, buildMockAIResponse } from '../data/mockData';
import FormField from '../components/Common/FormField';
import AIResponseView from '../components/AI/AIResponseView';
import LoadingSpinner from '../components/Common/LoadingSpinner';
import SuccessMessage from '../components/Common/SuccessMessage';
import ErrorMessage from '../components/Common/ErrorMessage';

export default function AIMentorPage() {
  const { projects, addAIHistory, addTask } = useData();

  const [projectId, setProjectId] = useState(projects[0]?.id ?? '');
  const [prompt, setPrompt] = useState('');
  const [taskType, setTaskType] = useState(aiTaskTypes[0]);
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');

  function handleGenerate(e) {
    e.preventDefault();
    setError('');
    if (!projectId) {
      setError('Please select a project.');
      return;
    }
    if (!prompt.trim()) {
      setError('Please enter a requirement or question.');
      return;
    }

    setLoading(true);
    setResponse(null);

    // Simulate the AI processing delay. The real call will be
    // generateAIPlan({ projectId, prompt, taskType }) to POST /api/ai/plan
    // on the FastAPI backend, which holds the Ollama/GPT-OSS API key.
    const projectName = projects.find((p) => p.id === Number(projectId))?.name ?? 'Unknown';
    setTimeout(() => {
      const mock = buildMockAIResponse(projectName, prompt.trim(), taskType);
      setResponse(mock);
      setLoading(false);
    }, 1400);
  }

  function handleSave() {
    if (!response) return;
    const projectName = projects.find((p) => p.id === Number(projectId))?.name ?? 'Unknown';
    addAIHistory({
      projectId: Number(projectId),
      projectName,
      taskType,
      userPrompt: prompt.trim(),
      responsePreview: response.recommendedNextAction.slice(0, 120),
      modelName: 'GPT-OSS',
      fullResponse: response,
    });
    setSuccess('Recommendation saved to AI History.');
  }

  // Create pending tasks from the frontend + backend task lists in the response.
  function handleCreateTasks() {
    if (!response) return;
    const baseTasks = [
      ...response.frontendTasks.map((t) => ({ title: t, category: 'Frontend' })),
      ...response.backendTasks.map((t) => ({ title: t, category: 'Backend' })),
      ...response.databaseTasks.map((t) => ({ title: t, category: 'Database' })),
    ];
    baseTasks.forEach((t) => {
      addTask({
        projectId: Number(projectId),
        title: t.title,
        description: `${t.category} task generated by AI Mentor.`,
        priority: 'Medium',
        status: 'Pending',
        aiGenerated: true,
      });
    });
    setSuccess(`${baseTasks.length} tasks created from the AI recommendation.`);
  }

  function handleClear() {
    setResponse(null);
    setPrompt('');
    setSuccess('');
    setError('');
  }

  return (
    <div>
      <div className="section-header">
        <h2>AI Mentor</h2>
      </div>

      {success ? <SuccessMessage message={success} onDismiss={() => setSuccess('')} /> : null}
      {error ? <ErrorMessage message={error} onDismiss={() => setError('')} /> : null}

      <div className="card mb-2">
        <form onSubmit={handleGenerate}>
          <div className="form-row">
            <FormField label="Select Project" htmlFor="ai-project" required>
              <select
                id="ai-project"
                className="form-select"
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
              >
                <option value="">— Select a project —</option>
                {projects.map((p) => (
                  <option key={p.id} value={p.id}>{p.name}</option>
                ))}
              </select>
            </FormField>

            <FormField label="AI Task Type" htmlFor="ai-task-type" required>
              <select
                id="ai-task-type"
                className="form-select"
                value={taskType}
                onChange={(e) => setTaskType(e.target.value)}
              >
                {aiTaskTypes.map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </FormField>
          </div>

          <FormField label="Requirement or Question" htmlFor="ai-prompt" required>
            <textarea
              id="ai-prompt"
              className="form-textarea"
              placeholder="Describe the requirement you want the AI Mentor to break down..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
          </FormField>

          <div className="page-actions">
            <button type="submit" className="btn btn-primary" disabled={loading}>
              <Sparkles size={16} /> Generate AI Recommendation
            </button>
          </div>
        </form>
      </div>

      {loading ? (
        <div className="card">
          <LoadingSpinner label="AI Mentor is analysing your project..." />
        </div>
      ) : null}

      {response ? (
        <div className="card">
          <div className="section-header">
            <h2>AI Recommendation</h2>
            <div className="page-actions">
              <button type="button" className="btn btn-secondary btn-sm" onClick={handleSave}>
                <Save size={15} /> Save Recommendation
              </button>
              <button type="button" className="btn btn-primary btn-sm" onClick={handleCreateTasks}>
                <PlusCircle size={15} /> Create Tasks from Recommendation
              </button>
              <button type="button" className="btn btn-secondary btn-sm" onClick={handleClear}>
                <Eraser size={15} /> Clear Response
              </button>
            </div>
          </div>
          <AIResponseView response={response} />
        </div>
      ) : null}
    </div>
  );
}
